// Package ros7api implements a client for the ROS7 (Mikrotik RouterOS 7) REST
// API (https://help.mikrotik.com/docs/display/ROS/REST+API).
//
// The API types are autogenerated from a high-level description. The main
// client and generated types are in the ros subpackage.
//
// The gen subpackage contains the code generator used to generate the API
// client types from a Protobuf description contained in gen/types.text.pb.
package ros7api
